version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080

  minio:
    image: 'bitnami/minio:latest'
    container_name: 'minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - 'MINIO_ROOT_USER=admin'
      - 'MINIO_ROOT_PASSWORD=password'
      - 'MINIO_DEFAULT_BUCKETS=cars'
